#### Merge the Geocoded Citations with Geocoded Arrests and Calls for Service

In [1]:
##setup
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [3]:
##import citations and arrests
citations = pd.read_csv('./Geocoding/data/civil_summons_2021_v6.csv')
arrests = pd.read_csv('./911_arrest /data/output/arrests_by_census_block_month_year.csv')

In [29]:
##import calls for service
calls = pd.read_csv('./911_arrest /data/output/final_calls_by_block_month_year.csv')

In [5]:
##check citations file
citations.head()

,Ticket_Number,Final_Officer_Tax_ID,Officer.first.name,Officer.last.name,cs_first,cs_middle,cs_last,pr_first,pr_middle,pr_last,Officer_Total_Summonses,month_issued,roster_rank,roster_command,roster_race,roster_gender,O_Violation_Date,O_Violation_Time,O_Issuing_Agency,O_Respondent_first_name,O_Respondent_last_name,O_Balance_Due,O_Violation_Location_Borough,O_Violation_Location_City,O_Violation_Location_Zip_Code,O_Violation_Location_State_Name,O_Respondent_Address_Borough,O_Hearing_Status,O_Hearing_Result,O_Scheduled_Hearing_Location,O_Hearing_Date,O_Hearing_Time,O_Decision_Location_Borough,O_Decision_Date,O_Total_Violation_Amount,O_Violation_Details,O_Date_Judgment_Docketed,O_Penalty_Imposed,O_Paid_Amount,O_Add_Penalties_Late_Fees,O_Compliance_Status,O_violation_location_borough,O_violation_location_block_no,O_violation_location_lot_no,O_violation_location_house_no,O_violation_location_street_name,O_violation_location_floor,O_violation_location_city,O_violation_location_zip_code,O_violation_location_state,O_respondent_address_borough,aa_felony_arrest_count,aa_misdemeanor_arrest_count,aa_violation_arrest_count,aa_infraction_arrest_count,aa_other_arrest_count,aa_total_arrests,commendation_award_count,excellent_award_count,meritorious_award_count,meritorious_integrity_award_count,exceptional_merit_award_count,total_award_count,Total.CCRB.complaints,Total.substantiated.CCRB.complaints,CCRB_Total_Allegations,CCRB_AmericanIndian_Allegations,CCRB_Asian_Allegations,CCRB_Black_Allegations,CCRB_Hispanic_Allegations,CCRB_White_Allegations,CCRB_Other_Allegations,CCRB_RefusedRace_Allegations,CCRB_Unknown_Allegations,CCRB_fado_Abuse of Authority,CCRB_fado_Discourtesy,CCRB_fado_Force,CCRB_fado_Offensive Language,CCRB_fado_Untruthful Statement,Reg.hours,Overtime.hours,Last.active,yrs_of_service,oath_latitude,oath_longitude,CB2020,CT2020,BCTCB2020,Respondent Race
0,190851430,953430,NICHOLAS,SORECA,NICHOLAS,V,SORECA,NICHOLAS,V,SORECA,1,2,SERGEANT,48.0,WHITE,MALE,2021-02-25,12:48:00,POLICE DEPARTMENT,NOAH,ANTWI,0.0,BRONX,BRONX,10457.0,NEW YORK,BRONX,NEW ISSUANCE,NaN,NaN,4/19/21,10:00:00,NaN,NaN,0.0,20210419,NaN,0.0,0.0,0,Penalty Due,BRONX,3143.0,130.0,2176,TIEBOUT AVENUE,NaN,BRONX,10457.0,NEW YORK,BRONX,25,92,0,0,0,115.0,0,1,0,0,0,1.0,1.0,1.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,2080.0,100.95,20301.0,13,40.854515,-73.898188,1002.0,38303.0,2.038303e+10,.
1,196184708,961743,PATRICIA,ENNIS,PATRICIA,NaN,ENNIS,PATRICIA,NaN,ENNIS,4,1,DETECTIVE,80.0,WHITE,FEMALE,2021-01-15,18:35:00,POLICE DEPARTMENT,KAZI,RAHMAN,0.0,BROOKLYN,BROOKLYN,11226.0,NEW YORK,BROOKLYN,HEARING COMPLETED,DISMISSED,BROOKLYN,6/4/21,9:00:00,SAU: MANH,6/11/21,100.0,20210604Y,NaN,0.0,0.0,0,All Terms Met,BROOKLYN,5219.0,22.0,1050,OCEAN AVENUE,NaN,BROOKLYN,11226.0,NEW YORK,BROOKLYN,24,39,1,0,0,63.0,0,0,0,0,0,0.0,4.0,0.0,2,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2080.0,256.83,20301.0,9,40.636648,-73.958646,1002.0,51800.0,3.051800e+10,Asian/Pacific Is.
2,196241834,961465,JAMES,WYNNE,JAMES,W,WYNNE,JAMES,W,WYNNE,1,1,POLICE OFFICER,116.0,WHITE,MALE,2021-01-04,17:20:00,POLICE DEPARTMENT,MARCELLE H,ARONSTEIN,0.0,QUEENS,QUEENS,NaN,NEW YORK,QUEENS,PAID IN FULL,NaN,NaN,2/24/21,9:00:00,NaN,NaN,250.0,20210224N,NaN,250.0,250.0,0,All Terms Met,QUEENS,NaN,NaN,NaN,INT OF CENTRAL AVE AND BEACH,NaN,QUEENS,NaN,NEW YORK,QUEENS,21,39,2,2,0,63.0,0,0,0,0,0,0.0,2.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2080.0,182.67,20301.0,10,40.607190,-73.749540,1009.0,103202.0,4.103202e+10,.
3,196242292,964085,MICHAEL,KENJESKY,MICHAEL,V,KENJESKY,MICHAEL,V,KENJESKY,1,3,POLICE OFFICER,116.0,WHITE,MALE,2021-03-02,9:48:00,POLICE DEPARTMENT,ALSTON T,WISHROPP,0.0,QUEENS,QUEENS,NaN,NEW YORK,QUEENS,HEARING COMPLETED,DISMISSED,NaN,4/21/21,9:30:00,BY PHONE,4/26/21,250.0,20210421N,NaN,0.0,0.0,0,All Terms Met,QUEENS,NaN,NaN,NaN,BEACH CHANNEL DRIVE MOTT AVE,NaN,QUEENS,NaN,NEW YORK,QUEENS,12,23,0,0,0,35.0,0,0,0,0,0,0.0,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2080.0,46.42,20301.0,8,40.605348,-73.755315,2005.0,103201.0,4.103201e+10,Black
4,196244840,964778,MICHAEL,SINTO,MICHAEL,G,SINTO,MICHAEL,G,SINTO,1,1,SERGEANT,89.0,WHITE,MALE,2021-01-01,21:40:00,POLICE DEPARTMENT,CARL,HARLESTON,0.0,QUEENS,FAR ROCKAWAY,11691.0,NEW YORK,NOT NYC,PAID IN FULL,IN VIOLATION,NaN,3/22/21,9:00:00,BY PHONE,3/22/21,250.0,20210217N,6/30/21,250.0,250.0,0,All Terms Met,QUEENS,15810.0,30.0,19-15,SEAGIRT BOULEVARD,NaN,FAR ROCKAWAY,11691.0,NEW YORK,NOT NYC,40,40,1,0,0,80.0,0,0,0,0,0,0.0,2.0,1.0,4,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,2080.0,379.42,20301.0,8,40.594817,-73.753899,3000.0,99802.0,4.099802e+10,Black

In [7]:
##convert the census level data to a string 
citations["BCTCB2020"] = citations["BCTCB2020"].astype(str)

In [9]:
##check arrests file
arrests.head()

   year  month     BCTCB2020  CB2020  CT2020  total_arrests
0  2020      1  1.000201e+10  1000.0   201.0              1
1  2020      1  1.000201e+10  1001.0   201.0              1
2  2020      1  1.000202e+10  1001.0   202.0              1
3  2020      1  1.000202e+10  2000.0   202.0              1
4  2020      1  1.000202e+10  4002.0   202.0              3

In [11]:
##convert census level data to a string
arrests["BCTCB2020"] = arrests["BCTCB2020"].astype(str)

In [13]:
##filter to only include arrests from 2021
arrests_2021 = arrests[arrests["year"] == 2021]

In [31]:
##check calls for service file
calls.head()

   year  month  CB2020   BoroName    CT2020     BCTCB2020  total_calls
0  2021      1     1.0   Brooklyn  102802.0  3.102802e+10            9
1  2021      1     1.0  Manhattan   16300.0  1.016300e+10            2
2  2021      1     2.0  Manhattan   13501.0  1.013501e+10            3
3  2021      1  1000.0      Bronx     100.0  2.000100e+10            2
4  2021      1  1000.0      Bronx     200.0  2.000200e+10            4

In [33]:
##convert census level data to a string
calls["BCTCB2020"] = calls["BCTCB2020"].astype(str)

In [15]:
##merge arrests w/ citations
citation_arrests_bctcb = citations.merge(arrests_2021, left_on=["month_issued", "BCTCB2020"], right_on=["month", "BCTCB2020"], how="left")
citation_arrests_bctcb.head()

,Ticket_Number,Final_Officer_Tax_ID,Officer.first.name,Officer.last.name,cs_first,cs_middle,cs_last,pr_first,pr_middle,pr_last,Officer_Total_Summonses,month_issued,roster_rank,roster_command,roster_race,roster_gender,O_Violation_Date,O_Violation_Time,O_Issuing_Agency,O_Respondent_first_name,O_Respondent_last_name,O_Balance_Due,O_Violation_Location_Borough,O_Violation_Location_City,O_Violation_Location_Zip_Code,O_Violation_Location_State_Name,O_Respondent_Address_Borough,O_Hearing_Status,O_Hearing_Result,O_Scheduled_Hearing_Location,O_Hearing_Date,O_Hearing_Time,O_Decision_Location_Borough,O_Decision_Date,O_Total_Violation_Amount,O_Violation_Details,O_Date_Judgment_Docketed,O_Penalty_Imposed,O_Paid_Amount,O_Add_Penalties_Late_Fees,O_Compliance_Status,O_violation_location_borough,O_violation_location_block_no,O_violation_location_lot_no,O_violation_location_house_no,O_violation_location_street_name,O_violation_location_floor,O_violation_location_city,O_violation_location_zip_code,O_violation_location_state,O_respondent_address_borough,aa_felony_arrest_count,aa_misdemeanor_arrest_count,aa_violation_arrest_count,aa_infraction_arrest_count,aa_other_arrest_count,aa_total_arrests,commendation_award_count,excellent_award_count,meritorious_award_count,meritorious_integrity_award_count,exceptional_merit_award_count,total_award_count,Total.CCRB.complaints,Total.substantiated.CCRB.complaints,CCRB_Total_Allegations,CCRB_AmericanIndian_Allegations,CCRB_Asian_Allegations,CCRB_Black_Allegations,CCRB_Hispanic_Allegations,CCRB_White_Allegations,CCRB_Other_Allegations,CCRB_RefusedRace_Allegations,CCRB_Unknown_Allegations,CCRB_fado_Abuse of Authority,CCRB_fado_Discourtesy,CCRB_fado_Force,CCRB_fado_Offensive Language,CCRB_fado_Untruthful Statement,Reg.hours,Overtime.hours,Last.active,yrs_of_service,oath_latitude,oath_longitude,CB2020_x,CT2020_x,BCTCB2020,Respondent Race,year,month,CB2020_y,CT2020_y,total_arrests
0,190851430,953430,NICHOLAS,SORECA,NICHOLAS,V,SORECA,NICHOLAS,V,SORECA,1,2,SERGEANT,48.0,WHITE,MALE,2021-02-25,12:48:00,POLICE DEPARTMENT,NOAH,ANTWI,0.0,BRONX,BRONX,10457.0,NEW YORK,BRONX,NEW ISSUANCE,NaN,NaN,4/19/21,10:00:00,NaN,NaN,0.0,20210419,NaN,0.0,0.0,0,Penalty Due,BRONX,3143.0,130.0,2176,TIEBOUT AVENUE,NaN,BRONX,10457.0,NEW YORK,BRONX,25,92,0,0,0,115.0,0,1,0,0,0,1.0,1.0,1.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,2080.0,100.95,20301.0,13,40.854515,-73.898188,1002.0,38303.0,20383031002.0,.,2021.0,2.0,1002.0,38303.0,1.0
1,196184708,961743,PATRICIA,ENNIS,PATRICIA,NaN,ENNIS,PATRICIA,NaN,ENNIS,4,1,DETECTIVE,80.0,WHITE,FEMALE,2021-01-15,18:35:00,POLICE DEPARTMENT,KAZI,RAHMAN,0.0,BROOKLYN,BROOKLYN,11226.0,NEW YORK,BROOKLYN,HEARING COMPLETED,DISMISSED,BROOKLYN,6/4/21,9:00:00,SAU: MANH,6/11/21,100.0,20210604Y,NaN,0.0,0.0,0,All Terms Met,BROOKLYN,5219.0,22.0,1050,OCEAN AVENUE,NaN,BROOKLYN,11226.0,NEW YORK,BROOKLYN,24,39,1,0,0,63.0,0,0,0,0,0,0.0,4.0,0.0,2,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2080.0,256.83,20301.0,9,40.636648,-73.958646,1002.0,51800.0,30518001002.0,Asian/Pacific Is.,2021.0,1.0,1002.0,51800.0,1.0
2,196241834,961465,JAMES,WYNNE,JAMES,W,WYNNE,JAMES,W,WYNNE,1,1,POLICE OFFICER,116.0,WHITE,MALE,2021-01-04,17:20:00,POLICE DEPARTMENT,MARCELLE H,ARONSTEIN,0.0,QUEENS,QUEENS,NaN,NEW YORK,QUEENS,PAID IN FULL,NaN,NaN,2/24/21,9:00:00,NaN,NaN,250.0,20210224N,NaN,250.0,250.0,0,All Terms Met,QUEENS,NaN,NaN,NaN,INT OF CENTRAL AVE AND BEACH,NaN,QUEENS,NaN,NEW YORK,QUEENS,21,39,2,2,0,63.0,0,0,0,0,0,0.0,2.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2080.0,182.67,20301.0,10,40.607190,-73.749540,1009.0,103202.0,41032021009.0,.,2021.0,1.0,1009.0,103202.0,1.0
3,196242292,964085,MICHAEL,KENJESKY,MICHAEL,V,KENJESKY,MICHAEL,V,KENJESKY,1,3,POLICE OFFICER,116.0,WHITE,MALE,2021-03-02,9:48:00,POLICE DEPARTMENT,ALSTON T,WISHROPP,0.0,QUEENS,QUEENS,NaN,NEW YORK,QUEENS,HEARING COMPLETED,DISMISSED,NaN,4/21/21,9:30:00,BY PHONE,4/26/21,250.0,20210421N,NaN,0.0,0.0,0,All Terms Met,QUEENS,NaN,NaN,NaN,BEACH CHANNEL DRIVE MOTT AVE,NaN,QUEENS,NaN,NEW YORK,QUEENS,12,23,0,0,0,35.0,0,0,0,0,0,0.0,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2080.0,46.42,20301.0,8,40.605348,-73.755315,2005.0,103201.0,41032012005.0,Black,NaN,NaN,NaN,NaN,NaN
4,196244840,964778,MICHAEL,SINTO,MICHAEL,G,SINTO,MICHAEL,G,SINTO,1,1,SERGEANT,89.0,WHITE,MALE,2021-01-01,21:40:00,POLICE DEPARTMENT,CARL,HARLESTON,0.0,QUEENS,FAR ROCKAWAY,11691.0,NEW YORK,NOT NYC,PAID IN FULL,IN VIOLATION,NaN,3/22/21,9:00:00,BY PHONE,3/22/21,250.0,20210217N,6/30/21,250.0,250.0,0,All Terms Met,QUEENS,15810.0,30.0,19-15,SEAGIRT BOULEVARD,NaN,FAR ROCKAWAY,11691.0,NEW YORK,NOT NYC,40,40,1,0,0,80.0,0,0,0,0,0,0.0,2.0,1.0,4,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,2080.0,379.42,20301.0,8,40.594817,-73.753899,3000.0,99802.0,40998023000.0,Black,NaN,NaN,NaN,NaN,NaN

In [17]:
##clean up column names
citation_arrests_bctcb.drop(columns=['year', 'month', 'CB2020_y', 'CT2020_y'], inplace=True)
citation_arrests_bctcb.rename(columns={'CB2020_x': 'CB2020', 'CT2020_x' : 'CT2020'}, inplace=True)

In [19]:
##clean NAs
citation_arrests_bctcb.loc[citation_arrests_bctcb['total_arrests'].isna(), 'total_arrests'] = 0

In [23]:
##check the merged file
citation_arrests_bctcb.head(25)

,Ticket_Number,Final_Officer_Tax_ID,Officer.first.name,Officer.last.name,cs_first,cs_middle,cs_last,pr_first,pr_middle,pr_last,Officer_Total_Summonses,month_issued,roster_rank,roster_command,roster_race,roster_gender,O_Violation_Date,O_Violation_Time,O_Issuing_Agency,O_Respondent_first_name,O_Respondent_last_name,O_Balance_Due,O_Violation_Location_Borough,O_Violation_Location_City,O_Violation_Location_Zip_Code,O_Violation_Location_State_Name,O_Respondent_Address_Borough,O_Hearing_Status,O_Hearing_Result,O_Scheduled_Hearing_Location,O_Hearing_Date,O_Hearing_Time,O_Decision_Location_Borough,O_Decision_Date,O_Total_Violation_Amount,O_Violation_Details,O_Date_Judgment_Docketed,O_Penalty_Imposed,O_Paid_Amount,O_Add_Penalties_Late_Fees,O_Compliance_Status,O_violation_location_borough,O_violation_location_block_no,O_violation_location_lot_no,O_violation_location_house_no,O_violation_location_street_name,O_violation_location_floor,O_violation_location_city,O_violation_location_zip_code,O_violation_location_state,O_respondent_address_borough,aa_felony_arrest_count,aa_misdemeanor_arrest_count,aa_violation_arrest_count,aa_infraction_arrest_count,aa_other_arrest_count,aa_total_arrests,commendation_award_count,excellent_award_count,meritorious_award_count,meritorious_integrity_award_count,exceptional_merit_award_count,total_award_count,Total.CCRB.complaints,Total.substantiated.CCRB.complaints,CCRB_Total_Allegations,CCRB_AmericanIndian_Allegations,CCRB_Asian_Allegations,CCRB_Black_Allegations,CCRB_Hispanic_Allegations,CCRB_White_Allegations,CCRB_Other_Allegations,CCRB_RefusedRace_Allegations,CCRB_Unknown_Allegations,CCRB_fado_Abuse of Authority,CCRB_fado_Discourtesy,CCRB_fado_Force,CCRB_fado_Offensive Language,CCRB_fado_Untruthful Statement,Reg.hours,Overtime.hours,Last.active,yrs_of_service,oath_latitude,oath_longitude,CB2020,CT2020,BCTCB2020,Respondent Race,total_arrests
0,190851430,953430,NICHOLAS,SORECA,NICHOLAS,V,SORECA,NICHOLAS,V,SORECA,1,2,SERGEANT,48.0,WHITE,MALE,2021-02-25,12:48:00,POLICE DEPARTMENT,NOAH,ANTWI,0.0,BRONX,BRONX,10457.0,NEW YORK,BRONX,NEW ISSUANCE,NaN,NaN,4/19/21,10:00:00,NaN,NaN,0.0,20210419,NaN,0.0,0.0,0,Penalty Due,BRONX,3143.0,130.0,2176,TIEBOUT AVENUE,NaN,BRONX,10457.0,NEW YORK,BRONX,25,92,0,0,0,115.0,0,1,0,0,0,1.0,1.0,1.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,2080.0,100.95,20301.0,13,40.854515,-73.898188,1002.0,38303.0,20383031002.0,.,1.0
1,196184708,961743,PATRICIA,ENNIS,PATRICIA,NaN,ENNIS,PATRICIA,NaN,ENNIS,4,1,DETECTIVE,80.0,WHITE,FEMALE,2021-01-15,18:35:00,POLICE DEPARTMENT,KAZI,RAHMAN,0.0,BROOKLYN,BROOKLYN,11226.0,NEW YORK,BROOKLYN,HEARING COMPLETED,DISMISSED,BROOKLYN,6/4/21,9:00:00,SAU: MANH,6/11/21,100.0,20210604Y,NaN,0.0,0.0,0,All Terms Met,BROOKLYN,5219.0,22.0,1050,OCEAN AVENUE,NaN,BROOKLYN,11226.0,NEW YORK,BROOKLYN,24,39,1,0,0,63.0,0,0,0,0,0,0.0,4.0,0.0,2,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2080.0,256.83,20301.0,9,40.636648,-73.958646,1002.0,51800.0,30518001002.0,Asian/Pacific Is.,1.0
2,196241834,961465,JAMES,WYNNE,JAMES,W,WYNNE,JAMES,W,WYNNE,1,1,POLICE OFFICER,116.0,WHITE,MALE,2021-01-04,17:20:00,POLICE DEPARTMENT,MARCELLE H,ARONSTEIN,0.0,QUEENS,QUEENS,NaN,NEW YORK,QUEENS,PAID IN FULL,NaN,NaN,2/24/21,9:00:00,NaN,NaN,250.0,20210224N,NaN,250.0,250.0,0,All Terms Met,QUEENS,NaN,NaN,NaN,INT OF CENTRAL AVE AND BEACH,NaN,QUEENS,NaN,NEW YORK,QUEENS,21,39,2,2,0,63.0,0,0,0,0,0,0.0,2.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2080.0,182.67,20301.0,10,40.607190,-73.749540,1009.0,103202.0,41032021009.0,.,1.0
3,196242292,964085,MICHAEL,KENJESKY,MICHAEL,V,KENJESKY,MICHAEL,V,KENJESKY,1,3,POLICE OFFICER,116.0,WHITE,MALE,2021-03-02,9:48:00,POLICE DEPARTMENT,ALSTON T,WISHROPP,0.0,QUEENS,QUEENS,NaN,NEW YORK,QUEENS,HEARING COMPLETED,DISMISSED,NaN,4/21/21,9:30:00,BY PHONE,4/26/21,250.0,20210421N,NaN,0.0,0.0,0,All Terms Met,QUEENS,NaN,NaN,NaN,BEACH CHANNEL DRIVE MOTT AVE,NaN,QUEENS,NaN,NEW YORK,QUEENS,12,23,0,0,0,35.0,0,0,0,0,0,0.0,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2080.0,46.42,20301.0,8,40.605348,-73.755315,2005.0,103201.0,41032012005.0,Black,0.0
4,196244840,964778,MICHAEL,SINTO,MICHAEL,G,SINTO,MICHAEL,G,SINTO,1,1,SERGEANT,89.0,WHITE,MALE,2021-01-01,21:40:00,POLICE DEPARTMENT,CARL,HARLESTON,0.0,QUEENS,FAR ROCKAWAY,11691.0,NEW YORK,NOT NYC,PAID IN FULL,IN VIOLATION,NaN,3/22/21,9:00:00,BY PHONE,3/22/21,250.0,20210217N,6/30/21,250.0,250.0,0,All Terms Met,QUEENS,15810.0,30.0,19-15,SEAGIRT BOULEVARD,NaN,FAR ROCKAWAY,11691.0,NEW YORK,NOT NYC,40,40,1,0,0,80.0,0,0,0,0,0,0.0,2.0,1.0,4,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,2080.0,379.42,20301.0,8,40.594817,-73.753899,3000.0,99802.0,40998023000.0,Black,0.0
5,196264925,963591,ERIN,KENNEDY,ERIN,L,KENNEDY,ERIN,L,KENNEDY,2,1,POLICE OFFICER,125.0,WHITE,FEMALE,2021-01-03,17:20:00,POLICE DEPARTMENT,PETER,RODRIGUEZ,0.0,QUEENS,QUEENS,NaN,NEW YORK,NOT NYC,HEARING COMPLETED,DISMISSED,NaN,2/22/21,9:00:00,BY PHONE,2/22/21,250.0,20210222N,NaN,0.0,0.0,0,All Terms Met,QUEENS,NaN,NaN,NaN,C O HILLSIDE AVE SPRINGFIELD,NaN,QUEENS,NaN,NEW YORK,NOT NYC,19,38,0,0,0,53.0,0,1,0,0,0,1.0,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2080.0,229.33,20059.0,8,40.729721,-73.744585,2000.0,55200.0,40552002000.0,Hisp. White,0.0
6,196269581,963656,MARISSA,DINIS,MARISSA,L,DINIS,MARISSA,L,MONACO,1,2,POLICE OFFICER,125.0,WHITE,FEMALE,2021-02-28,19:55:00,POLICE DEPARTMENT,PRIYA,BHUSHAN,0.0,QUEENS,QUEENS,NaN,NEW YORK,QUEENS,HEARING COMPLETED,DISMISSED,NaN,4/21/21,9:00:00,BY PHONE,4/21/21,250.0,20210421N,NaN,0.0,0.0,0,All Terms Met,QUEENS,NaN,NaN,NaN,UNION TURNPIKE 270 ST,NaN,QUEENS,NaN,NEW YORK,QUEENS,15,33,0,0,0,45.0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2080.0,195.33,20301.0,8,40.751271,-73.703829,6003.0,157901.0,41579016003.0,Asian/Pacific Is.,0.0
7,196320722,952904,FREDDY,JONES,FREDDY,NaN,JONES,FREDDY,NaN,JONES,1,2,POLICE OFFICER,158.0,BLACK,MALE,2021-02-06,22:00:00,POLICE DEPARTMENT,JOSHUA,ADAMS,25.0,MANHATTAN,NEW YORK,10037.0,NEW YORK,NOT NYC,DEFAULTED,DEFAULTED,MANHATTAN,3/29/21,9:00:00,NaN,4/5/21,25.0,20210329N,6/4/21,25.0,0.0,0,Penalty Due,MANHATTAN,1756.0,69.0,2,EAST 132 STREET,NaN,NEW YORK,10037.0,NEW YORK,NOT NYC,35,203,21,1,0,260.0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2080.0,260.08,19236.0,13,40.810553,-73.938685,1000.0,20600.0,10206001000.0,Black,0.0
8,196374613,966902,ANTHONY,VELAZQUEZ,ANTHONY,F,VELAZQUEZ,ANTHONY,F,VELAZQUEZ,3,1,POLICE OFFICER,1057.0,HISPANIC,MALE,2021-01-05,19:05:00,POLICE DEPARTMENT,MICHAEL I,UDECHI,250.0,MANHATTAN,NEW YORK,NaN,NEW YORK,MANHATTAN,DOCKETED,DEFAULTED,MANHATTAN,2/24/21,9:00:00,NaN,3/3/21,250.0,20210224N,6/30/21,250.0,0.0,0,Penalty Due,MANHATTAN,NaN,NaN,NaN,S E C O WEST 143 STREET 8TH,NaN,NEW YORK,NaN,NEW YORK,MANHATTAN,16,35,5,0,0,56.0,0,0,0,0,0,0.0,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2080.0,377.92,20301.0,7,40.821957,-73.943829,2001.0,25900.0,10259002001.0,Black,1.0
9,196380892,966375,JOSEPH,VADALA,JOSEPH,NaN,VADALA,JOSEPH,G,VADALA,1,1,POLICE OFFICER,131.0,WHITE,MALE,2021-01-23,21:15:00,POLICE DEPARTMENT,RAY C,WALKER,0.0,BROOKLYN,BROOKLYN,11221.0,NEW YORK,BROOKLYN,HEARING COMPLETED,DISMISSED,NaN,3/15/21,9:00:00,BROOKLYN,3/9/21,0.0,20210315,NaN,0.0,0.0,0,All Terms Met,BROOKLYN,1815.0,8.0,532,GATES AVENUE,NaN,BROOKLYN,11221.0,NEW YORK,BROOKLYN,0,0,0,0,0,28.0,0,0,0,0,0,4.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2068.6,62.33,18779.0,7,40.686796,-73.944372,3000.0,26500.0,30265003000.0,Black,0.0
10,196384421,966645,JOSE,JIMENEZ,JOSE,A,JIMENEZ,JOSE,A,JIMENEZ,3,2,SERGEANT,1145.0,HISPANIC,MALE,2021-02-20,20:55:00,POLICE DEPARTMENT,ASHTON,WOMACK,25.0,BROOKLYN,BROOKLYN,11221.0,NEW YORK,BROOKLYN,DEFAULTED,DEFAULTED,BROOKLYN,7/13/21,9:00:00,NaN,7/20/21,25.0,20210713Y,9/20/21,25.0,0.0,0,Penalty Due,BROOKLYN,1820.0,43.0,416,MONROE STREET,NaN,BROOKLYN,11221.0,NEW YORK,BROOKLYN,27,56,2,0,0,74.0,0,0,0,0,0,0.0,1.0,1.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2080.0,436.50,20301.0,7,40.686281,-73.941791,4000.0,26500.0,30265004000.0,Black,1.0
11,196384440,964591,MUHAMMAD,KHALIQUE,MUHAMMAD,S,KHALIQUE,MUHAMMAD,S,KHALIQUE,5,3,POLICE OFFICER,98.0,ASIAN,MALE,2021-03-20,14:45:00,POLICE DEPARTMENT,ZACHARY L,SPIEZER,0.0,BROOKLYN,BROOKLYN,NaN,NEW YORK,NOT NYC,PAID IN FULL,NaN,BROOKLYN,8/18/21,9:00:00,NaN,NaN,100.0,20210818Y,NaN,100.0,100.0,0,All Terms Met,BROOKLYN,NaN,NaN,NaN,N W CORNER MARCUS GARVEY HAL,NaN,BROOKLYN,NaN,NEW YORK,NOT NYC,6,25,1,0,0,32.0,0,0,0,0,0,0.0,1.0,0.0,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2080.0,234.92,20301.0,8,40.683168,-73.938080,3001.0,27500.0,30275003001.0,White,2.0
12,196384843,966613,SREEKANTH,HARIDAS,SREEKANTH,NaN,HARIDAS,SREEKANTH,NaN,HARIDAS,4,3,POLICE OFFICER,98.0,ASIAN,MALE,2021-03-19,18:20:00,POLICE DEPARTMENT,ANGEL V,AUCAMA,25.0,BROOKLYN,BROOKLYN,11206.0,NEW YORK,QUEENS,DEFAULTED,DEFAULTED,BROOKLYN,8/18/21,9:30:00,NaN,8/25/21,25.0,20210818Y,10/25/21,25.0,0.0,0,Penalty Due,BROOKLYN,1732.0,19.0,180,THROOP AVENUE,NaN,BROOKLYN,11206.0,NEW YORK,QUEENS,0,0,0,0,0,16.0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2080.0,200.33,18841.0,7,40.698830,-73.944421,2000.0,25700.0,30257002000.0,Hisp. White,0.0
13,196384861,966613,SREEKANTH,HARIDAS,SREEKANTH,NaN,HARIDAS,SREEKANTH,NaN,HARIDAS,4,3,POLICE OFFICER,98.0,ASIAN,MALE,2021-03-27,20:05:00,POLICE DEPARTMENT,PRINCE,HOBSON,1.0,BROOKLYN,BROOKLYN,11216.0,NEW YORK,NOT NYC,HEARING COMPLETED,IN VIOLATION,SAU: BKLN,8/18/21,9:30:00,BY PHONE,8/24/21,25.0,20210818Y,10/25/21,1.0,0.0,0,Penalty Due,BROOKLYN,1863.0,21.0,1450,FULTON STREET,NaN,BROOKLYN,11216.0,NEW YORK,NOT NYC,0,0,0,0,0,16.0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2080.0,200.33,18841.0,7,40.679861,-73.942766,1004.0,27100.0,30271001004.0,Black,1.0
14,196385907,966888,MARITZA,TORRES,MARITZA,NaN,TORRES,NaN,NaN,NaN,2,2,POLICE OFFICER,993.0,HISPANIC,FEMALE,2021-02-14,18:50:00,POLICE DEPARTMENT,SHAWN M,LAKE,5.0,BROOKLYN,BROOKLYN,NaN,NEW YORK,BROOKLYN,HEARING COMPLETED,IN VIOLATION,SAU: BKLN,4/15/21,9:30:00,BY PHONE,4/21/21,25.0,20210415N,6/21/21,5.0,0.0,0,Penalty Due,BROOKLYN,NaN,NaN,NaN,NOSTRAND AVE I O LEXINGTON,NaN,BROOKLYN,NaN,NEW YORK,BROOKLYN,0,0,0,0,0,0.0,0,0,0,0,0,NaN,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,17987.0,0,40.687670,-73.951036,2000.0,24300.0,30243002000.0,White,2.0
15,196385925,966858,NECIBE,SINMAZISIK,NECIBE,NaN,SINMAZISIK,NECIBE,NaN,SINMAZISIK,3,2,POLICE OFFICER,98.0,WHITE,FEMALE,2021-02-11,20:15:00,POLICE DEPARTMENT,DANIEL,MALIN,100.0,BROOKLYN,BROOKLYN,NaN,NEW YORK,BROOKLYN,DOCKETED,DEFAULTED,BROOKLYN,4/2/21,9:30:00,NaN,4/9/21,100.0,20210402N,7/31/21,100.0,0.0,0,Penalty Due,BROOKLYN,NaN,NaN,NaN,NOSTRAND AVE I O KOSCUISZKO,NaN,BROOKLYN,NaN,NEW YORK,BROOKLYN,15,16,0,1,0,32.0,0,0,0,0,0,0.0,2.0,1.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2080.0,410.92,20301.0,7,40.690600,-73.951615,2000.0,24100.0,30241002000.0,Black,0.0
16,196386530,966441,GREGORY,ANTOINE,GREGORY,NaN,ANTOINE,GREGORY,NaN,ANTOINE,1,1,POLICE OFFICER,1064.0,BLACK,MALE,2021-01-31,0:37:00,POLICE DEPARTMENT,KEVIN,BOLANOS,25.0,BROOKLYN,BROOKLYN,11216.0,NEW YORK,NOT NYC,DEFAULTED,DEFAULTED,BROOKLYN,6/25/21,9:30:00,NaN,7/2/21,25.0,20210625Y,8/31/21,25.0,0.0,0,Penalty Due,BROOKLYN,1775.0,66.0,707,DEKALB AVENUE,NaN,BROOKLYN,11216.0,NEW YORK,NOT NYC,3,10,1,0,0,14.0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2080.0,240.33,20301.0,7,40.692020,-73.947730,4001.0,26100.0,30261004001.0,White,0.0
17,196386960,966548,TROY,DRISCOLL,TROY,J,DRISCOLL,TROY,J,DRISCOLL,2,3,POLICE OFFICER,98.0,WHITE,MALE,2021-03-04,19:19:00,POLICE DEPARTMENT,JOSE,REYES,0.0,BROOKLYN,BROOKLYN,11216.0,NEW YORK,BROOKLYN,NEW ISSUANCE,NaN,NaN,4/26/21,9:30:00,NaN,NaN,0.0,20210426,NaN,0.0,0.0,0,All Terms Met,BROOKLYN,1808.0,51.0,784,MARCY AVENUE,NaN,BROOKLYN,11216.0,NEW YORK,BROOKLYN,13,24,0,0,0,36.0,0,0,0,0,0,0.0,7.0,1.0,20,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,11.0,1.0,8.0,0.0,0.0,2080.0,231.58,20301.0,7,40.686684,-73.947862,3000.0,25100.0,30251003000.0,Hisp. White,2.0
18,196387080,966728,DANIEL,MUCCIACCIO,DANIEL,J,MUCCIACCIO,DANIEL,J,MUCCIACCIO,2,3,POLICE OFFICER,98.0,WHITE,MALE,2021-03-26,20:30:00,POLICE DEPARTMENT,ERIC,HANNAH,25.0,BROOKLYN,BROOKLYN,NaN,NEW YORK,NOT NYC,DEFAULTED,DEFAULTED,BROOKLYN,8/18/21,9:00:00,NaN,8/25/21,25.0,20210818Y,10/25/21,25.0,0.0,0,Penalty Due,BROOKLYN,NaN,NaN,NaN,I O TOMPKINS AVE LEXINGTON A,NaN,BROOKLYN,NaN,NEW YORK,NOT NYC,10,26,0,0,0,17.0,0,0,0,0,0,0.0,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2080.0,253.33,20301.0,7,40.688375,-73.944921,1004.0,26300.0,30263001004.0,Black,58.0
19,196396018,959907,LOREAL,VASQUEZ,LOREAL,NaN,VASQUEZ,LOREAL,NaN,VASQUEZ,2,3,POLICE OFFICER,107.0,HISPANIC,FEMALE,2021-03-14,11:30:00,POLICE DEPARTMENT,FRANK,SOBERS,0.0,BROOKLYN,BROOKLYN,11217.0,NEW YORK,BROOKLYN,HEARING COMPLETED,DISMISSED,SAU: BKLN,7/23/21,9:00:00,BY PHONE,7/27/21,250.0,20210723Y,NaN,0.0,0.0,0,All Terms Met,BROOKLYN,2097.0,143.0,10,FT GREENE PLACE,NaN,BROOKLYN,11217.0,NEW YORK,BROOKLYN,20,22,0,0,0,42.0,0,2,0,0,0,2.0,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2080.0,0.00,20301.0,10,40.689479,-73.977222,2000.0,3300.0,30033002000.0,Black,0.0
20,196403498,960914,KEITH,MCGREEVY,KEITH,NaN,MCGREEVY,NaN,NaN,NaN,1,2,POLICE OFFICER,139.0,WHITE,MALE,2021-02-27,21:03:00,POLICE DEPARTMENT,JOSEPH T,HARDWICK,25.0,BROOKLYN,BROOKLYN,11211.0,NEW YORK,BROOKLYN,DEFAULTED,DEFAULTED,BROOKLYN,7/23/21,9:00:00,NaN,7/30/21,25.0,20210723Y,9/28/21,25.0,0.0,0,Penalty Due,BROOKLYN,2413.0,20.0,301,UNION AVENUE,NaN,BROOKLYN,11211.0,NEW YORK,BROOKLYN,0,0,0,0,0,0.0,0,0,0,0,0,NaN,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,18631.0,0,40.709491,-73.951106,3010.0,51300.0,30513003010.0,White,0.0
21,196425058,965833,MICHAEL,QUIZHPI,MICHAEL,P,QUIZHPI,MICHAEL,NaN,QUIZHPI,2,3,POLICE OFFICER,93.0,HISPANIC,MALE,2021-03-18,11:10:00,POLICE DEPARTMENT,ANTHONY J,THOMAS,0.0,BROOKLYN,BROOKLYN,11238.0,NEW YORK,NOT NYC,PAID IN FULL,NaN,BROOKLYN,5/7/21,9:30:00,NaN,NaN,100.0,20210507N,NaN,100.0,100.0,0,All Terms Met,BROOKLYN,1145.0,1.0,623,VANDERBILT AVENUE,NaN,BROOKLYN,11238.0,NEW YORK,NOT NYC,18,15,0,0,0,29.0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2080.0,347.83,20301.0,7,40.678594,-73.968184,1002.0,20500.0,30205001002.0,Black,0.0
22,196425561,956627,DHARINA,ESTEVEZ,DHARINA,C,ESTEVEZ,DHARINA,C,ESTEVEZ,1,2,SERGEANT,105.0,HISPANIC,FEMALE,2021-02-20,15:00:00,POLICE DEPARTMENT,JOSE S,NUNEZ,250.0,BROOKLYN,BROOKLYN,NaN,NEW YORK,NOT NYC,DOCKETED,DEFAULTED,BROOKLYN,7/13/21,9:30:00,NaN,7/20/21,250.0,20210713Y,10/31/21,250.0,0.0,0,Penalty Due,BROOKLYN,NaN,NaN,NaN,I O EASTERN PKWY ROCHESTER A,NaN,BROOKLYN,NaN,NEW YORK,NOT NYC,21,54,2,1,0,78.0,0,1,0,0,0,1.0,3.0,0.0,3,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,2080.0,707.42,20301.0,11,40.668866,-73.928337,2001.0,34901.0,30349012001.0,Hisp. White,2.0
23,196427761,967292,ZAID,RIAZ,ZAID,NaN,RIAZ,ZAID,NaN,RIAZ,1,3,POLICE OFFICER,93.0,ASIAN,MALE,2021-03-25,19:25:00,POLICE DEPARTMENT,DARRIUS,JOHNSON,25.0,NOT NYC,NaN,NaN,NEW YORK,NOT NYC,DEFAULTED,DEFAULTED,NaN,5/14/21,9:00:00,NaN,5/21/21,25.0,20210514,7/20/21,25.0,0.0,0,Penalty Due,NOT NYC,NaN,NaN,NaN,STERLING PL UTICA AVE,NaN,NaN,NaN,NEW YORK,NOT NYC,6,10,0,0,0,16.0,0,0,0,0,0,0.0,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2080.0,332.92,19389.0,7,40.671483,-73.930873,1000.0,34500.0,30345001000.0,Black,0.0
24,196440283,961052,ERDEM,OZEN,ERDEM,NaN,OZEN,ERDEM,NaN,OZEN,2,1,SERGEANT,1140.0,WHITE,MALE,2021-01-13,6:40:00,POLICE DEPARTMENT,REY,SUTHERLAND,0.0,BROOKLYN,BROOKLYN,NaN,NEW YORK,BROOKLYN,HEARING COMPLETED,DISMISSED,BROOKLYN,3/4/21,9:30:00,SAU: MANH,3/12/21,50.0,20210304N,NaN,0.0,0.0,0,All Terms Met,BROOKLYN,NaN,NaN,NaN,LORIMER ST I O METROPOLITAN,NaN,BROOKLYN,NaN,NEW YORK,BROOKLYN,33,52,10,1,0,95.0,0,1,0,0,0,1.0,2.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2080.0,107.58,20301.0,10,40.714066,-73.949372,3000.0,50300.0,30503003000.0,Hisp. White,1.0

In [35]:
##merge the citation/arrest file with calls for service by census data
citation_arrests_calls = citation_arrests_bctcb.merge(calls, left_on=["month_issued", "BCTCB2020"], right_on=["month", "BCTCB2020"], how="left")
citation_arrests_calls.head()

,Ticket_Number,Final_Officer_Tax_ID,Officer.first.name,Officer.last.name,cs_first,cs_middle,cs_last,pr_first,pr_middle,pr_last,Officer_Total_Summonses,month_issued,roster_rank,roster_command,roster_race,roster_gender,O_Violation_Date,O_Violation_Time,O_Issuing_Agency,O_Respondent_first_name,O_Respondent_last_name,O_Balance_Due,O_Violation_Location_Borough,O_Violation_Location_City,O_Violation_Location_Zip_Code,O_Violation_Location_State_Name,O_Respondent_Address_Borough,O_Hearing_Status,O_Hearing_Result,O_Scheduled_Hearing_Location,O_Hearing_Date,O_Hearing_Time,O_Decision_Location_Borough,O_Decision_Date,O_Total_Violation_Amount,O_Violation_Details,O_Date_Judgment_Docketed,O_Penalty_Imposed,O_Paid_Amount,O_Add_Penalties_Late_Fees,O_Compliance_Status,O_violation_location_borough,O_violation_location_block_no,O_violation_location_lot_no,O_violation_location_house_no,O_violation_location_street_name,O_violation_location_floor,O_violation_location_city,O_violation_location_zip_code,O_violation_location_state,O_respondent_address_borough,aa_felony_arrest_count,aa_misdemeanor_arrest_count,aa_violation_arrest_count,aa_infraction_arrest_count,aa_other_arrest_count,aa_total_arrests,commendation_award_count,excellent_award_count,meritorious_award_count,meritorious_integrity_award_count,exceptional_merit_award_count,total_award_count,Total.CCRB.complaints,Total.substantiated.CCRB.complaints,CCRB_Total_Allegations,CCRB_AmericanIndian_Allegations,CCRB_Asian_Allegations,CCRB_Black_Allegations,CCRB_Hispanic_Allegations,CCRB_White_Allegations,CCRB_Other_Allegations,CCRB_RefusedRace_Allegations,CCRB_Unknown_Allegations,CCRB_fado_Abuse of Authority,CCRB_fado_Discourtesy,CCRB_fado_Force,CCRB_fado_Offensive Language,CCRB_fado_Untruthful Statement,Reg.hours,Overtime.hours,Last.active,yrs_of_service,oath_latitude,oath_longitude,CB2020_x,CT2020_x,BCTCB2020,Respondent Race,total_arrests,year,month,CB2020_y,BoroName,CT2020_y,total_calls
0,190851430,953430,NICHOLAS,SORECA,NICHOLAS,V,SORECA,NICHOLAS,V,SORECA,1,2,SERGEANT,48.0,WHITE,MALE,2021-02-25,12:48:00,POLICE DEPARTMENT,NOAH,ANTWI,0.0,BRONX,BRONX,10457.0,NEW YORK,BRONX,NEW ISSUANCE,NaN,NaN,4/19/21,10:00:00,NaN,NaN,0.0,20210419,NaN,0.0,0.0,0,Penalty Due,BRONX,3143.0,130.0,2176,TIEBOUT AVENUE,NaN,BRONX,10457.0,NEW YORK,BRONX,25,92,0,0,0,115.0,0,1,0,0,0,1.0,1.0,1.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,2080.0,100.95,20301.0,13,40.854515,-73.898188,1002.0,38303.0,20383031002.0,.,1.0,2021.0,2.0,1002.0,Bronx,38303.0,56.0
1,196184708,961743,PATRICIA,ENNIS,PATRICIA,NaN,ENNIS,PATRICIA,NaN,ENNIS,4,1,DETECTIVE,80.0,WHITE,FEMALE,2021-01-15,18:35:00,POLICE DEPARTMENT,KAZI,RAHMAN,0.0,BROOKLYN,BROOKLYN,11226.0,NEW YORK,BROOKLYN,HEARING COMPLETED,DISMISSED,BROOKLYN,6/4/21,9:00:00,SAU: MANH,6/11/21,100.0,20210604Y,NaN,0.0,0.0,0,All Terms Met,BROOKLYN,5219.0,22.0,1050,OCEAN AVENUE,NaN,BROOKLYN,11226.0,NEW YORK,BROOKLYN,24,39,1,0,0,63.0,0,0,0,0,0,0.0,4.0,0.0,2,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2080.0,256.83,20301.0,9,40.636648,-73.958646,1002.0,51800.0,30518001002.0,Asian/Pacific Is.,1.0,2021.0,1.0,1002.0,Brooklyn,51800.0,22.0
2,196241834,961465,JAMES,WYNNE,JAMES,W,WYNNE,JAMES,W,WYNNE,1,1,POLICE OFFICER,116.0,WHITE,MALE,2021-01-04,17:20:00,POLICE DEPARTMENT,MARCELLE H,ARONSTEIN,0.0,QUEENS,QUEENS,NaN,NEW YORK,QUEENS,PAID IN FULL,NaN,NaN,2/24/21,9:00:00,NaN,NaN,250.0,20210224N,NaN,250.0,250.0,0,All Terms Met,QUEENS,NaN,NaN,NaN,INT OF CENTRAL AVE AND BEACH,NaN,QUEENS,NaN,NEW YORK,QUEENS,21,39,2,2,0,63.0,0,0,0,0,0,0.0,2.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2080.0,182.67,20301.0,10,40.607190,-73.749540,1009.0,103202.0,41032021009.0,.,1.0,2021.0,1.0,1009.0,Queens,103202.0,15.0
3,196242292,964085,MICHAEL,KENJESKY,MICHAEL,V,KENJESKY,MICHAEL,V,KENJESKY,1,3,POLICE OFFICER,116.0,WHITE,MALE,2021-03-02,9:48:00,POLICE DEPARTMENT,ALSTON T,WISHROPP,0.0,QUEENS,QUEENS,NaN,NEW YORK,QUEENS,HEARING COMPLETED,DISMISSED,NaN,4/21/21,9:30:00,BY PHONE,4/26/21,250.0,20210421N,NaN,0.0,0.0,0,All Terms Met,QUEENS,NaN,NaN,NaN,BEACH CHANNEL DRIVE MOTT AVE,NaN,QUEENS,NaN,NEW YORK,QUEENS,12,23,0,0,0,35.0,0,0,0,0,0,0.0,1.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2080.0,46.42,20301.0,8,40.605348,-73.755315,2005.0,103201.0,41032012005.0,Black,0.0,2021.0,3.0,2005.0,Queens,103201.0,241.0
4,196244840,964778,MICHAEL,SINTO,MICHAEL,G,SINTO,MICHAEL,G,SINTO,1,1,SERGEANT,89.0,WHITE,MALE,2021-01-01,21:40:00,POLICE DEPARTMENT,CARL,HARLESTON,0.0,QUEENS,FAR ROCKAWAY,11691.0,NEW YORK,NOT NYC,PAID IN FULL,IN VIOLATION,NaN,3/22/21,9:00:00,BY PHONE,3/22/21,250.0,20210217N,6/30/21,250.0,250.0,0,All Terms Met,QUEENS,15810.0,30.0,19-15,SEAGIRT BOULEVARD,NaN,FAR ROCKAWAY,11691.0,NEW YORK,NOT NYC,40,40,1,0,0,80.0,0,0,0,0,0,0.0,2.0,1.0,4,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,2080.0,379.42,20301.0,8,40.594817,-73.753899,3000.0,99802.0,40998023000.0,Black,0.0,2021.0,1.0,3000.0,Queens,99802.0,183.0

In [37]:
##clean up column names
citation_arrests_calls.drop(columns=['year', 'month', 'CB2020_y', 'CT2020_y'], inplace=True)
citation_arrests_calls.rename(columns={'CB2020_x': 'CB2020', 'CT2020_x' : 'CT2020'}, inplace=True)

In [39]:
##get the total number of rows with no calls for service
citation_arrests_calls['total_calls'].isna().sum()

205

In [41]:
##clean NAs
citation_arrests_calls.loc[citation_arrests_calls['total_calls'].isna(), 'total_calls'] = 0

In [43]:
##export to csv
citation_arrests_calls.to_csv('./civil_summons_2021_v7.csv', index = False)